### ISSUE TITLE
Document memberships and roles API endpoints

### ISSUE THREAD

**Issue by colemanm** [fulcrumapp/developer.fulcrumapp.com#10]
Add docs for these two endpoints.

**Comment by AHelms** [comment]
Century Engineering is looking for this and a few others as well.

ref: https://app.intercom.io/a/apps/nxff46cx/inbox/unassigned/conversations/6045961942

**Comment by utumno86** [comment]
documented the memberships API here: https://github.com/fulcrumapp/developer.fulcrumapp.com/pull/39

**Comment by utumno86** [comment]
Threw roles api documentation into the above PR to satisfy this issue.

**Comment by utumno86** [comment]
Addressed in todays release
