### ISSUE TITLE
Add search capability

### ISSUE THREAD

**Issue by colemanm** [fulcrumapp/developer.fulcrumapp.com#11]
Not sure if we should have one mega search option or different search fields for each section, but this could be particularly useful as the examples lib gets built out.

**Comment by bmcbride** [comment]
Search is currently available for expression functions: http://developer.fulcrumapp.com/expressions/reference/

**Comment by JasonSanford** [comment]
I'll add this in for the data event functions too.

**Comment by JasonSanford** [comment]
Fixed in 4cec8f6dce6440869803b1eef44867b5b7123c9e
