### ISSUE TITLE
Add padding to anchor points

### ISSUE THREAD

**Issue by campbell17** [fulcrumapp/developer.fulcrumapp.com#13]
We need to add a conditional class to the h2s that serve as anchor points - when the submenu sticks, there should be enough top padding to see the heading below the fixed menu. In short, in should jump to the correct heading with 10-15px (above it) to spare.

![anchor-alignment](https://cloud.githubusercontent.com/assets/601126/12023869/108c4478-ad6c-11e5-8f4b-ebe98b854e51.gif)

**Comment by JasonSanford** [comment]
Fixed in 730747c16b6d90f4995457659e60290bd40f5bad
