### ISSUE TITLE
Make the example titles consistent

### ISSUE THREAD

**Issue by zhm** [fulcrumapp/developer.fulcrumapp.com#23]
Some of the example titles `Are In Title Case` and others are `In normal sentence case`.

**Comment by oeon** [comment]
`.` consistency too in descriptions, etc.

**Comment by zhm** [comment]
I think we should drop the Title Case probably, some of them are long enough to not be very title-y sounding. Thoughts?

**Comment by oeon** [comment]
+1

**Comment by bmcbride** [comment]
Closed by d0e38fe
