### ISSUE TITLE
Missing API doc information

### ISSUE THREAD

**Issue by AHelms** [fulcrumapp/developer.fulcrumapp.com#28]
This was reported by a user.

- Status.required 
- Status.disabled 
- Status.default_previous_value
- Form Element property "default_values" 
- FormElement.default_previous_value
- FormElement.pattern and FormElement.pattern_description

ref: https://app.intercom.io/a/apps/nxff46cx/inbox/alex@fulcrumapp.com/conversations/6181801634

**Comment by bmcbride** [comment]
Closed by https://github.com/fulcrumapp/developer.fulcrumapp.com/commit/70d595e0ab591888d654d33159154a98124251de
