### ISSUE TITLE
Add note on forms API

### ISSUE THREAD

**Issue by AHelms** [fulcrumapp/developer.fulcrumapp.com#36]
Add note that 'Key' values for fields must be lowercase. Uppercase keys will cause various issues. 

One known result of using uppercase key values is if the field is being used as a record title and the app is being used in a record link field. The pick list in the record link field will fail to populate and result in a 500 error.

**Comment by bmcbride** [comment]
Docs have been updated to reflect this.

**Comment by AHelms** [comment]
Awesome thanks!
