### ISSUE TITLE
Create alternate logo for developers.fulcrumapp

### ISSUE THREAD

**Issue by campbell17** [fulcrumapp/developer.fulcrumapp.com#4]
Create something along the lines of what slack does for their API section:

![image](https://cloud.githubusercontent.com/assets/601126/10582012/9df43ae6-7653-11e5-9eb9-2a4f4724b5a1.png)

Not necessary, but would be nice.

**Comment by colemanm** [comment]
I like that - like we discussed, even some separate color theme would work to differentiate the developer section.
