### ISSUE TITLE
Document pagination in API docs

### ISSUE THREAD

**Issue by colemanm** [fulcrumapp/developer.fulcrumapp.com#9]
Right now you sort of have to guess at the pagination parameters you need to pass by looking at what's returned in the index views. We should add a section quickly outlining this in the root of the API docs.

**Comment by bmcbride** [comment]
You mean expand on this: http://developer.fulcrumapp.com/api/intro/#pagination? The `per-page` parameter is documented individually for each API endpoint. See: http://developer.fulcrumapp.com/endpoints/records/#query-parameters

**Comment by bmcbride** [comment]
I think this has been documented in the new docs. Feel free to re-open if I'm mistaken.
